<a href="https://colab.research.google.com/github/SusanBP97/APIpy/blob/main/TablaPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install tabula-py[jpype]
import tabula
import pandas as pd

Collecting tabula-py[jpype]
  Downloading tabula_py-2.10.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.12/dist-packages (from tabula-py[jpype]) (2.2.2)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.12/dist-packages (from tabula-py[jpype]) (2.0.2)
Requirement already satisfied: distro in /usr/local/lib/python3.12/dist-packages (from tabula-py[jpype]) (1.9.0)
Collecting jpype1 (from tabula-py[jpype])
  Downloading jpype1-1.7.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.3 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->tabula-py[jpype]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->tabula-py[jpype]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->tabula-py[jpype]) (2026.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from jpype1->tabula-py[jpype]) (26.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->tabula-py[jpype]) (1.17.0)
Downloading jpype1-1.7.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (438 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 438.5/438.5 kB 18.8 MB/s eta 0:00:00
Downloading tabula_py-2.10.0-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 73.4 MB/s eta 0:00:00
Installing collected packages: jpype1, tabula-py
Successfully installed jpype1-1.7.1 tabula-py-2.10.0

In [4]:
tablas  = tabula.read_pdf("sb2.pdf",pages= "all",multiple_tables=False,)

In [5]:
df=tablas[0]
print(df.head(10))

  Edición                  Fecha                   Ganador Marcador  \
0       I  15 de\renero\rde 1967        Green Bay\rPackers  35 - 10
1      II  14 de\renero\rde 1968    Green Bay\rPackers (2)  33 - 14
2     III  12 de\renero\rde 1969             New York Jets   16 - 7
3      IV  11 de\renero\rde 1970       Kansas City\rChiefs   23 - 7
4       V  17 de\renero\rde 1971           Baltimore Colts  16 - 13
5      VI  16 de\renero\rde 1972            Dallas Cowboys   24 - 3
6     VII  14 de\renero\rde 1973            Miami Dolphins   14 - 7
7    VIII  13 de\renero\rde 1974       Miami Dolphins\r(2)   24 - 7
8      IX  12 de\renero\rde 1975      Pittsburgh\rSteelers   16 - 6
9       X  18 de\renero\rde 1976  Pittsburgh\rSteelers (2)  21 - 17

                 Perdedor                             Estadio  \
0     Kansas City\rChiefs      Los Angeles Memorial\rColiseum
1         Oakland Raiders                   Miami Orange Bowl
2         Baltimore Colts               Miami Orange Bowl (2)
3      Minnesota\rVikings                      Tulane Stadium
4          Dallas Cowboys               Miami Orange Bowl (3)
5          Miami Dolphins                  Tulane Stadium (2)
6    Washington\rRedskins  Los Angeles Memorial\rColiseum (2)
7  Minnesota\rVikings (2)                        Rice Stadium
8  Minnesota\rVikings (3)                  Tulane Stadium (3)
9     Dallas Cowboys\r(2)               Miami Orange Bowl (4)

                         Ciudad
0       Los Ángeles, California
1                Miami, Florida
2            Miami, Florida (2)
3      Nueva Orleans,\rLuisiana
4            Miami, Florida (3)
5  Nueva Orleans,\rLuisiana (2)
6  Los Ángeles, California\r(2)
7                Houston, Texas
8  Nueva Orleans,\rLuisiana (3)
9            Miami, Florida (4)

In [15]:
df

,Edición,Fecha,Ganador,Marcador,Perdedor,Estadio,Ciudad
0,I,15 deenerode 1967,Green Bay\rPackers,35 - 10,Kansas City\rChiefs,Los Angeles MemorialColiseum,"[Los Ángeles, California]"
1,II,14 deenerode 1968,Green Bay\rPackers (2),33 - 14,Oakland Raiders,Miami Orange Bowl,"[Miami, Florida]"
2,III,12 deenerode 1969,New York Jets,16 - 7,Baltimore Colts,Miami Orange Bowl (2),"[Miami, Florida (2)]"
3,IV,11 deenerode 1970,Kansas City\rChiefs,23 - 7,Minnesota\rVikings,Tulane Stadium,"[Nueva Orleans,Luisiana]"
4,V,17 deenerode 1971,Baltimore Colts,16 - 13,Dallas Cowboys,Miami Orange Bowl (3),"[Miami, Florida (3)]"
...,...,...,...,...,...,...,...
57,LVIII,11 defebrerode 2024,Kansas City\rChiefs (4),25 - 22[2],San Francisco\r49ers (3),Allegiant Stadium,"[Paradise, Nevada]"
58,LIX,9 defebrerode 2025,Philadelphia\rEagles (2),40 - 22,Kansas City\rChiefs (3),Caesars Superdome (8),"[Nueva Orleans,Luisiana (11)]"
59,LX,8 defebrerode 2026,NaN,NaN,NaN,Levi's Stadium (2),"[Santa Clara, California(3)]"
60,LXI,14 defebrerode 2027,NaN,NaN,NaN,SoFi Stadium (2),"[Inglewood, California(9)]"
61,LXII,13 defebrerode 2028,NaN,NaN,NaN,Mercedes-Benz Stadium(2),"[Atlanta, Georgia (4)]"

In [13]:
df['Fecha']=df['Fecha'].str.replace('\r','')
df['Ciudad'] =df['Ciudad'].str.replace('\r','').str.rsplit('(0123456789)')
df['Estadio']=df['Estadio'].str.replace('\r','')

In [14]:
df

,Edición,Fecha,Ganador,Marcador,Perdedor,Estadio,Ciudad
0,I,15 deenerode 1967,Green Bay\rPackers,35 - 10,Kansas City\rChiefs,Los Angeles MemorialColiseum,"[Los Ángeles, California]"
1,II,14 deenerode 1968,Green Bay\rPackers (2),33 - 14,Oakland Raiders,Miami Orange Bowl,"[Miami, Florida]"
2,III,12 deenerode 1969,New York Jets,16 - 7,Baltimore Colts,Miami Orange Bowl (2),"[Miami, Florida (2)]"
3,IV,11 deenerode 1970,Kansas City\rChiefs,23 - 7,Minnesota\rVikings,Tulane Stadium,"[Nueva Orleans,Luisiana]"
4,V,17 deenerode 1971,Baltimore Colts,16 - 13,Dallas Cowboys,Miami Orange Bowl (3),"[Miami, Florida (3)]"
...,...,...,...,...,...,...,...
57,LVIII,11 defebrerode 2024,Kansas City\rChiefs (4),25 - 22[2],San Francisco\r49ers (3),Allegiant Stadium,"[Paradise, Nevada]"
58,LIX,9 defebrerode 2025,Philadelphia\rEagles (2),40 - 22,Kansas City\rChiefs (3),Caesars Superdome (8),"[Nueva Orleans,Luisiana (11)]"
59,LX,8 defebrerode 2026,NaN,NaN,NaN,Levi's Stadium (2),"[Santa Clara, California(3)]"
60,LXI,14 defebrerode 2027,NaN,NaN,NaN,SoFi Stadium (2),"[Inglewood, California(9)]"
61,LXII,13 defebrerode 2028,NaN,NaN,NaN,Mercedes-Benz Stadium(2),"[Atlanta, Georgia (4)]"